### ISSUE TITLE
Cleanup the GDG name

### ISSUE THREAD

**Issue by omarmiatello** [kevinsimper/gdg-search#52]
To improve the readability/search I suggest using something like `cleanGdgName()` in https://github.com/omarmiatello/gdg-events-ktor/blob/master/src/main/kotlin/utils/DataExtensions.kt

This is an example extracted from my repo (in Kotlin):

```kotlin
fun cleanGdgName(originalName: String) = originalName.replaceAfter(" - ", "")
    .replace("\u0027", "'")
    .replace("Google Developer Group", "GDG", ignoreCase = true)
    .replace("GDG-", "GDG ", ignoreCase = true)
    .replace("Google Cloud Developer Community", "GCDC", ignoreCase = true)
    .replace("GCDC-", "GCDC", ignoreCase = true)
    .replace("Meetup", "", ignoreCase = true)
    .replace("GDG (GDG)", "GDG")
    .replace("GDG GDG", "GDG")
    .replace(" - ", "")
    .replace(" ", " ")
    .trim()
```

**Comment by kevinsimper** [comment]
Hi Omar 😄

So that would give us the City of where it is in. Would that be different from the City column on the frontpage?
![image](https://user-images.githubusercontent.com/1126497/80955646-e700fd00-8dff-11ea-8cfb-c2e3387c9058.png)
